apiVersion: csmc.devminer.xyz/v1alpha1
kind: GameMode
metadata:
  name: arena
spec:
  image: "ghcr.io/community-sourced-minecraft/game-servers:operated@sha256:18f54f68555ae44890761f2a6babe73e138d109c32c6a6e202fe81c8ae011ee8"
  # TODO: Autoscale these pods
  replicas: 1
  networkRef: csmc
  args: ["arena"]
