apiVersion: csmc.devminer.xyz/v1alpha1
kind: GameMode
metadata:
  name: arena
spec:
  image: "ghcr.io/community-sourced-minecraft/game-servers:main@sha256:5cb3437e9e1470ad9f777aefde62f59a92eae7e05eed4dd133df13f9a5044f62"
  # TODO: Autoscale these pods
  replicas: 1
  networkRef: csmc
  args: ["arena"]
