apiVersion: csmc.devminer.xyz/v1alpha1
kind: GameMode
metadata:
  name: arena
spec:
  image: "ghcr.io/community-sourced-minecraft/game-servers:operated"
  # TODO: Autoscale these pods
  replicas: 3
  networkRef: csmc
  args: ["arena"]
