apiVersion: csmc.devminer.xyz/v1alpha1
kind: GameMode
metadata:
  name: arena
spec:
  image: "ghcr.io/community-sourced-minecraft/game-servers:operated@sha256:7d5541cd0b5c030d9031828952d429765d6ad6a4c5643b3719deec73c7b418da"
  # TODO: Autoscale these pods
  replicas: 1
  networkRef: csmc
  args: ["arena"]
