apiVersion: csmc.devminer.xyz/v1alpha1
kind: GameMode
metadata:
  name: lobby
spec:
  image: "ghcr.io/community-sourced-minecraft/game-servers:operated@sha256:f3ee1c654b027a5948e1fad6d1d5550070ae7caa158388edf9bb47f91f938395"
  # TODO: Autoscale these pods
  replicas: 3
  networkRef: csmc
  args: ["lobby"]