apiVersion: csmc.devminer.xyz/v1alpha1
kind: GameMode
metadata:
  name: lobby
spec:
  image: "ghcr.io/community-sourced-minecraft/game-servers:operated@sha256:085b0c33acb59fc7541f58fb9fd1390acf9756c3fd06b85e6602724261f6e03a"
  # TODO: Autoscale these pods
  replicas: 3
  networkRef: csmc
  args: ["lobby"]