apiVersion: csmc.devminer.xyz/v1alpha1
kind: GameMode
metadata:
  name: lobby
spec:
  image: "ghcr.io/community-sourced-minecraft/game-servers:operated@sha256:d482c98ab0d91a940beeed6525ad7834078f9b18fcd3c95792cf9d72af74856b"
  # TODO: Autoscale these pods
  replicas: 3
  networkRef: csmc
  args: ["lobby"]