apiVersion: csmc.devminer.xyz/v1alpha1
kind: Proxy
metadata:
  name: proxy
spec:
  image: "ghcr.io/community-sourced-minecraft/proxy:main@sha256:1eb86e0484d714298960a1f2f0bd9703c1020cc042abfbea15fef6906a61adac"
  networkRef: csmc
  port: 30000

---
apiVersion: csmc.devminer.xyz/v1alpha1
kind: Proxy
metadata:
  name: proxy-experimental
spec:
  image: "ghcr.io/community-sourced-minecraft/proxy:main@sha256:1eb86e0484d714298960a1f2f0bd9703c1020cc042abfbea15fef6906a61adac"
  networkRef: csmc
  port: 30001
