apiVersion: csmc.devminer.xyz/v1alpha1
kind: Proxy
metadata:
  name: proxy
spec:
  image: "ghcr.io/community-sourced-minecraft/proxy:operated@sha256:500eee7f2821d7e17385891cdb1705bbad4cefe3d4eec65da51dd9dd9f91c1fb"
  networkRef: csmc